version: "3"
services:
    proxy:
        container_name: proxy
        image: urvaius/jc-proxy:latest
        build:
            context: ./Proxy
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - client
            - api
            - certbot
        links:
            - client
            - api
            - certbot
        networks:
            - jc
        ports:
            - 80:80
            - 443:443
        expose:
            - 80
            - 443
        volumes:
            - ./nginx/conf/:/etc/nginx/conf.d/:ro
            - ./certbot/www/:/var/www/certbot/:ro
    certbot:
        image: urvaius/jc-certbot:latest
        build:
            context: ./CertBot
            dockerfile: Dockerfile
        networks:
            - jc
        volumes:
            - ./certbot/www/:/var/www/certbot/:rw
            - ./certbot/conf/:/etc/letsencrypt/:rw
    sqlserver:
        container_name: sqlserver
        image: urvaius/jc-sqlserver:latest
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Buffy11$
        build:
            context: ./SQLServer
            dockerfile: Dockerfile
        restart: always
        networks:
            - jc
        ports:
            - 1433:1433
        expose:
            - 1433
        volumes:
            - ./appdata:/appdata
    client:
        container_name: client
        image: urvaius/jc-client:latest
        build:
            context: ./Client
            dockerfile: Dockerfile
        depends_on:
            - api
        links:
            - api
        networks:
            - jc
        ports:
            - 9000:9000
        expose:
            - 9000
        volumes:
            - ./appdata:/appdata
    api:
        container_name: api
        image: urvaius/jc-api:latest
        build:
            context: ./API
            dockerfile: Dockerfile
        depends_on:
            - sqlserver
        volumes:
            - ./appdata:/appdata
        networks:
            - jc
        ports:
            - 5000:5000
        expose:
            - 5000
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        env_file: jc-development-secrets.env

networks:
    jc:
        name: jc
        driver: bridge
        